Squashed 'deps/libgit2/' changes from 8b2670b1ce9..d1cfd79a477
d1cfd79a477 Merge pull request #5045 from cheese1/patch-1
67562b232ae fix typo
c4cd69b2582 Merge pull request #5039 from libgit2/ethomson/win32_hash
5a190ad31d7 Merge pull request #5040 from pks-t/pks/ignore-treat-dirpaths-as-dir
9d117e20119 ignore: treat paths with trailing "/" as directories
aeea1c46394 Merge pull request #4874 from tiennou/test/4615
80db20430ec Merge pull request #5034 from pks-t/pks/symlinked-user-config
6bcb7357ecc Merge pull request #5035 from pks-t/pks/diff-with-space-in-filenames
fb7614c0f3d tests: test largefiles on win32
18e836cbf3f Merge pull request #5018 from romkatv/strings
e5aecaf62a6 sha1: don't inline `git_hash_global_init` for win32
30a56ba644e optimize string comparisons
9aa049d4c15 Merge pull request #5020 from implausible/fix/gitignore-negation
8cf3fd93a17 tests: config: assure that we can read symlinked global configuration
b3ba2e716b3 tests: config: verify that the global config is actually readable
25c085e6e0b tests: repo: verify that we can open repos with symlinked global config
9d65360b4ea tests: diff: test parsing diffs with a new file with spaces in its path
b3497344fa5 patch_parse: fix parsing addition/deletion of file with space
131cd9b16db patch_parse: improve formatting
5f188c48aaf Merge pull request #5024 from stewid/xdiff-fix-typo
fa4505e6f1e tests: config: make sure to clean up after each test
675251d168e Merge pull request #5032 from eaigner/checkout-force-safe-docfix
bbba4805e74 docs: clarify relation of safe and forced checkout strategy
7f1ba1969b0 Merge pull request #5026 from tenderlove/define-hash-global-init-consnstently
be9a386ceda Each hash implementation should define `git_hash_global_init`
d87441f2bde ignore: move tests from status to attr ignore suite
1a349003865 xdiff: fix typo
b50e448b3cb ignore: add additional test cases
e3d7bccbec2 ignore: Do not match on prefix of negated patterns
bc74c53a377 Implement failing test for gitignore of complex subdirectory negation
8e4927a44b2 Merge pull request #5012 from dritter/dritter-patch-1
1fd0903ae2e Update URL to git2-rs
79b26f20a68 Merge pull request #5008 from libgit2/ethomson/remote_completion
7b083d3cd37 Merge pull request #5005 from libgit2/ethomson/odb_backend_allocations
c7e5eca6a30 Revert "foo"
1fe3fa5e598 foo
b401273b028 Merge branch 'threading-docs'
02ab4841b9d threading: clarify openssl default vs mbedtls
358a3b9c382 threading: clarify concurrency of access
2dd5a429416 remote: Rename git_remote_completion_type to _t
68729289213 Merge pull request #5000 from augfab/branch_lookup_all
459ac856d94 odb: provide a free function for custom backends
790aae778df odb: rename git_odb_backend_malloc for consistency
c5d8e3006d9 branch: have git_branch_lookup accept GIT_BRANCH_ALL
0a25141e7b3 branch: add test for git_branch_lookup to accept GIT_BRANCH_ALL
bd132046b04 p_fallocate: compatibility fixes for macOS
0345a380a09 p_fallocate: add a test for our implementation
7ab7bf46b86 p_fallocate: don't duplicate definitions for win32
32f50452073 p_fallocate: add Windows emulation
5a6a3c00acb Merge pull request #4997 from libgit2/ethomson/transfer_progress
ca909da5dd9 remote: deprecate git_push_transfer_progress
59001e83057 remote: rename git_push_transfer_progress callback
7506d34c0ca indexer: deprecate git_transfer_progress
a1ef995dc03 indexer: use git_indexer_progress throughout
975d6722a5c indexer: rename git_transfer_progress
4069f924855 Merge pull request #4901 from pks-t/pks/uniform-map-api
75dd7f2acc0 Merge pull request #4984 from pks-t/pks/refdb-fs-race
c5594852ac3 Merge pull request #4998 from pks-t/pks/allocator-restructuring
3aa8401a8fd Merge pull request #4992 from pks-t/pks/cache-dispose
68ba2e8d16f Merge pull request #4956 from pks-t/pks/examples-cgit2-standalone
bbdcd45055c cache: fix misnaming of `git_cache_free`
765ff6e029a allocators: make crtdbg allocator reuse its own realloc
48727e5d3bc allocators: extract crtdbg allocator into its own file
b63396b75fe allocators: move standard allocator into subdirectory
9eb098d8614 Merge pull request #4991 from libgit2/ethomson/inttypes
247e6d909ac Remove public 'inttypes.h' header
554b3b9aa59 Merge pull request #4996 from eaigner/master
966b944095e tests: apply: verify that we correctly truncate the source buffer
014d49559ac apply: prevent OOB read when parsing source buffer
6eb4947d05d Merge pull request #4987 from lhchavez/fix-odb_otype_fast-leak
6b3730d4b99 Fix a memory leak in odb_otype_fast()
12c6e1facc1 Merge pull request #4986 from lhchavez/realloc
9f388e9f9ee Merge pull request #4990 from libgit2/remove_time_monotonic
d900dde4cf8 Merge pull request #4988 from lhchavez/fix-improbable-odb-initialization-leak
e6c6d3bb3d3 Remove `git_time_monotonic`
cb150e60558 Merge pull request #4989 from libgit2/ethomson/ci_docs
fbfa41a1aff ci: publish documentation on merge
b5b3aa93957 Revert "ci: publish documentation after merge"
4a02d24a8c0 foo
484fff87e60 foo
2a4e866a43e ci: publish documentation after merge
dd45539d547 Fix a _very_ improbable memory leak in git_odb_new()
6e0dfc6ffab Make stdalloc__reallocarray call stdalloc__realloc
df42f3689bb idxmap: remove legacy low-level interface
bd66925a615 oidmap: remove legacy low-level interface
4713e7c87ed offmap: remove legacy low-level interface
fdfabdc4e26 strmap: remove legacy low-level interface
6a9117f557f cache: use iteration interface for cache eviction
c976b4f9b30 indexer: use map iterator to delete expected OIDs
18cf56989af maps: provide high-level iteration interface
c50a8ac2c73 maps: use high-level function to check existence of keys
84a089da370 maps: provide return value when deleting entries
8da93944f3d idxmap: have `resize` functions return proper error code
661fc57b2cd idxmap: introduce high-level setter for key/value pairs
d00c24a9dd1 idxmap: introduce high-level getter for values
b9d0b664071 offmap: introduce high-level setter for key/value pairs
aa2456239b4 offmap: introduce high-level getter for values
2e0a3048397 oidmap: introduce high-level setter for key/value pairs
9694ef2064b oidmap: introduce high-level getter for values
03555830784 strmap: introduce high-level setter for key/value pairs
ef507bc7bdd strmap: introduce `git_strmap_get` and use it throughout the tree
7e926ef3061 maps: provide a uniform entry count interface
351eeff3b2a maps: use uniform lifecycle management functions
6cf47726845 examples/add: add explanatory comments and reformat
106998fce6e examples: print available commands if no args are given
ead10785dcd examples: create common lg2 executable
7562422ab93 examples: merge common network code
c4271314e10 examples: remove unused Makefile
a540e6bbcbb examples: remove test script
94743daf2ef refdb_fs: fix race when migrating loose to packed refs in iteration
3ff0e3b5c31 refdb_fs: remove ordering dependency on loose/packed refs loading
833338144a6 refdb_fs: do not lazily copy packed ref cache
32063d82a14 refdb_fs: refactor error handling in iterator creation
8c77343871c refdb_fs: fix potential race with ref repacking in `exists` callback
bda0839734b Merge pull request #4982 from pks-t/pks/worktree-add-bare-head
48005936a7a Merge pull request #4965 from hackworks/eliminate-check-for-keep-file
b88378278bd Merge pull request #4979 from libgit2/ethomson/deprecate
bf013fc0a8c branch: fix `branch_is_checked_out` with bare repos
efb20825e16 branches: introduce flag to skip enumeration of certain HEADs
788cd2d5f07 branches: do not assert that the given ref is a branch
a0f87e161b0 branches: add tests for `git_branch_is_checked_out`
698eae1392e worktree: error out early if given ref is not valid
3f823c2bd85 ci: enable hard deprecation
dcf81cdbcc1 deprecation: optionally enable hard deprecation
24ac9e0c97f deprecation: ensure we GIT_EXTERN deprecated funcs
e19163761d5 Merge pull request #4980 from libgit2/ethomson/ci_nightly
ef91917f73c ci: skip ssh tests on macOS nightly
85b2bd41bea Merge pull request #4976 from libgit2/ethomson/readme_v028
811c1c0f8f8 ci: skip ssh tests on macOS
44f8213480e ci: provide more information about OS
6f778351bb3 README: use correct badge for nightlies
f34faaa8f3c README: include build badge for v0.28 builds
582d036dfb5 Update threading.md
004a339874e Allow bypassing check '.keep' files using libgit2 option 'GIT_OPT_IGNORE_PACK_KEEP_FILE_CHECK'
1a107fac0fc Merge pull request #4970 from libgit2/ethomson/0_28
3fe29c4d4cf version: 0.28
63f96cd0639 changelog: this is 0.28
214457c68e5 Merge pull request #4968 from tiennou/fix/documentation
6853a250071 Merge branch 'pks/stream-truncated-writes'
0ceac0d0ce5 mbedtls: fix potential size overflow when reading or writing data
75918aba1d0 mbedtls: make global variables static
657197e6541 openssl: fix potential size overflow when writing data
7613086df46 streams: handle short writes only in generic stream
5265b31cc5a streams: fix callers potentially only writing partial data
193e7ce979c streams: make file-local functions static
9fd9126ee7b docs: minor changes
2f1d6eff31d Merge pull request #4954 from tiennou/fix/documentation
4e3949b73e2 tests: test that largefiles can be read through the tree API
cf14215deda Merge pull request #4964 from libgit2/ethomson/ci_nightly
52a97eed430 ci: add coverity badge to the README
0cf5b6b17d1 ci: ignore coverity failures in nightly runs
690e55e0021 repo: split git_repository_open_flag_t options documentation inline
f6412c26c15 transport: enhance documentation
2964fed0c5d docs: document GIT_EUSER/GIT_EPASSTHROUGH
9e4d421edd4 doc: clarify that git_time_t is seconds from the epoch
e9a34864784 Merge pull request #4961 from libgit2/ethomson/ci_docurium
92b52f36519 Merge pull request #4962 from libgit2/ethomson/ci_nightly
08d71f72dd2 ci: return coverity to the nightlies
b1e286254a1 Merge pull request #4950 from libgit2/ethomson/warnings
f56634f803e Merge pull request #4869 from libgit2/ethomson/ci_nightly
ace20c6a88e ci: run docurium to create documentation
4a798a91162 nightly: use latest images, not test images
fac08837a50 filter: return an int
89bd4ddb33a diff_generate: validate oid file size
fd9d4e28b28 describe: don't mix and match abbreviated size types
751eb46247e delta: validate sizes and cast safely
4947216fa52 git transport: only write INT_MAX bytes
a861839d098 windows: add SSIZE_MAX
f1986a23d8e streams: don't write more than SSIZE_MAX
e5e2fac8211 buffer: explicitly cast
f4ebb2d4e8d blame: make hunk_cmp handle unsigned differences
ae681d3ff5b apply: make update_hunk accept a size_t
7ed2baf7b18 MSVC: ignore empty compilation units (warning LNK4221)
3fba5891ef9 test: cast to a char the zstream test
f25bb508cf7 index test: cast times explicitly
1d4ddb8ecf3 iterator: cast filesystem iterator entry values explicitly
c6cac733c14 blob: validate that blob sizes fit in a size_t
3aa6d96a230 tree: cast filename length in git_tree__parse_raw
759502ed305 odb_loose: explicitly cast to size_t
80c3867b760 patch: explicitly cast down in parse_header_percent
494448a5eb7 index: explicitly cast down to a size_t
c3866fa87cf diff: explicitly cast in flush_hunk
826d9a4de88 Merge pull request #4858 from tiennou/fix/index-ext-read
859d92292e0 Merge pull request #4952 from libgit2/ethomson/deprecation
c951b825bcf deprecation: define GIT_DEPRECATE_HARD internally
9f3a5a64b5f deprecation: offer GIT_DEPRECATE_HARD
9c5e05ad762 deprecation: move deprecated tests into their own file
e09f0c10179 deprecation: don't use deprecated stream cb
09e2ea2fe11 deprecation: provide docurium deprecation note
53d13fb3e83 deprecation: deprecated stream registration in if guard
769e92749be deprecation: update changelog to reflect new policies
a7d0d14fb03 deprecation: move deprecated bits to deprecated.h
1c3daccf1ad fuzzers: don't use deprecated types
cc5da0a63de examples: don't use deprecated types
5524a467586 Merge pull request #4957 from csware/deprecated
bff7aed23bb Don't use deprecated constants
0bf7e0433dc index: preserve extension parsing errors
80be19b90e4 Merge pull request #4955 from csware/c4098
53bf0bde9ad Fix VS warning C4098: 'giterr_set_str' : void function returning a value
635693d3bc5 Merge pull request #4917 from libgit2/ethomson/giterr
a27a4de6f80 errors: update docs for giterr changes
00c66dfd3b5 errors: update static analysis tools for giterr
fcc7dcb1762 errors: remove giterr usage in examples
115a6c50c9c errors: remove giterr usage in fuzzers
f673e232afe git_error: use new names in internal APIs and usage
647dfdb42d0 git_error: deprecate error values
20961b9871f git_error: use full class name in public error API
6b2cd0ed599 Merge pull request #4949 from zlikavac32/fix-odb-foreach-cb-positive-error-code
f7416509c06 Fix odb foreach to also close on positive error code
68166017dc3 Merge pull request #4948 from libgit2/ethomson/memleaks
b8b796c14a2 repository: free memory in symlink detection function
1e92a0363db Merge pull request #4947 from libgit2/ethomson/proxyupdate
c9d9e25fb1b ci: update poxyproxy, run in quiet mode
86b522bdefa Merge pull request #4945 from libgit2/ethomson/fix-intrinsics
b5a3ef3cc6b Merge pull request #4944 from libgit2/ethomson/deprecation
75444d97fd5 add with overflow: correct documentation
abbc07f12fd add with overflow: use SizeTAdd on Windows
c6d47acfbfd Remove unused git__add_uint64_overflow
f04f1c7eedf add with overflow intrinsics: simplify tests
1b2af79e857 deprecation: use the enum type in declaration
44827b6764d deprecation: add `used` attribute
1758636b13a Merge pull request #4939 from libgit2/ethomson/git_ref
b2c2dc643b2 Merge pull request #4940 from libgit2/ethomson/git_obj
c352e5617ac Merge pull request #4943 from libgit2/ethomson/ci
e2b9f56878d ci: run all invasive tests on windows
1ebf3a7decc ci: only run invasive tests during nightly runs
6b8a648f6f3 ci: clear settings variables in powershell
423d3e738ae ci: precisely identify the invasive tests
4e0c8a1e731 Merge pull request #4930 from libgit2/ethomson/cdecl
38e61797b57 changelog: document that we always build cdecl
22d2062d954 Introduce GIT_CALLBACK macro to enforce cdecl
57b753a0dc0 cmake: error when STDCALL is specified
a74dd39b232 Use cdecl calling conventions on Win32
b78bcbb9b12 buffer: wrap EXTERN in DEPRECATED
6e17bfda574 Merge pull request #4932 from libgit2/ethomson/changelog
6a0e94572b2 changelog: document git_merge_analysis_for_ref
35be7f1f287 changelog: document openssl fixes
85feb28a1bf changelog: document core.logallrefupdates=always
a6e5d46bb1e fixup! changelog: document changes since 0.27
1bb03f7ac17 changelog: document changes since 0.27
abe23675793 Merge pull request #4925 from lhchavez/fix-a-bunch-of-warnings
cecbe7462de Merge pull request #4941 from libgit2/ethomson/mailmap
d4cbe9ef3d6 mailmap: prefer ethomson@edwardthomson.com
83151018ef0 object_type: convert final internal users to new names
cd350852206 object_type: GIT_OBJECT_BAD is now GIT_OBJECT_INVALID
90046899572 object_type: mark old values as deprecated
ed8cfbf0418 references: use new names in internal usage
87fe5788919 references: use full name in type names
628ebc5168c Merge pull request #4937 from lhchavez/fix-crlf
7a43a892860 Convert tests/resources/push.sh to LF endings
2c795807f76 Merge pull request #4936 from implausible/remove/unnecessary-test-files
a653f967811 Get rid of some test files that were accidentally committed
5b08a71fcbf Merge pull request #4934 from stinb/proxy-crash
35d86c775bb proxy: fix crash on remote connection with GIT_PROXY_AUTO but no proxy is detected
54ae052859a tests: fix test expectation mismatch
1b4ba8443fe ci: enable some of the invasive testcases
3c6d1979546 ci: move coverity in its own pipeline
99afd41f1c4 Merge pull request #4924 from lhchavez/werror
3afa1ede022 Merge pull request #4931 from tiennou/cmake/osx-deprecated-warn
2cc66dd5039 cmake: remove unconditional -Wno-deprecated-declaration on APPLE
6af6170b684 Make ENABLE_WERROR actually work
2848923a2f5 Let GCC use the add/mul overflow intrinsics
c6bfaf14cff Explanation for the rationale behind splitting formatting
1305cd4e8df Merge pull request #4926 from csware/warning-c4133
924f61bfb5a Merge pull request #4928 from lhchavez/fix-warnings
728101e3c53 Move the intrinsics part of the change to its own PR
8b5995283c3 Fix Linux warnings
19bca3d33c8 Merge pull request #4922 from tiennou/fix/coverity-cids
450019061be Fix warning 'function': incompatible types - from 'git_cvar_value *' to 'int *' (C4133) on VS
321d19c1058 Windows is hard.
b5e8272fdca Attempt at fixing the MingW64 compilation
7b453e7e39c Fix a bunch of warnings
a74f4fb9d27 coverity: attempt to model clar's assertions
50d4688c316 tests: add missing asserts
d9eae98b571 refs: assert that we're passed valid refs when renaming
0a8745f25c0 diff: assert that we're passed a valid git_diff object
9c23552c380 submodule: grab the error while loading from config
9f714dec3ae config: assert that our parameters are valid
fba70a9d5f1 Merge pull request #4919 from pks-t/pks/shutdown-cb-count
9084712b555 Merge pull request #4904 from libgit2/ethomson/crlf
b46c35943a2 global: move init callbacks into an array
03dc6480b41 hash: convert `global_init` macros to real function
e385e6474eb checkout::crlf: ensure success
77f1460fcf6 Merge pull request #4915 from pks-t/pks/refdb-minor-refactorings
8dde7e1137a refdb_fs: refactor error handling in `refdb_reflog_fs__delete`
bc219657546 Merge pull request #4833 from csware/drop-empty-dirs
2a9b0102fc9 Additional core.autocrlf and core.safecrlf tests
ef8f8ec6040 crlf: update to match git's logic
59b054cb7ef index::crlf: better error reporting in core git tests
021a08b09e2 index::crlf: simplify test case
e417fd990e7 crlf tests: use known-good data produced by git
3d804063d90 crlf_data: add corpus of known-good odb-filtered data
a0ab90b8819 crlf: re-use existing crlf script to create odb
9065160bfb5 crlf: script to generate expected crlf data for adding files to index
c3169e6f629 checkout::crlf clear the crlf workdir for checkout
13a8bc924c1 crlf_data: move to a "to_workdir" folder
9f48dc3b73b Remove empty directories when deleting refs

git-subtree-dir: deps/libgit2
git-subtree-split: d1cfd79a477a440c5f0929c34e817da202227ec7